# Generated by Django 5.1.5 on 2025-02-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='test',
            name='assessment_id',
            field=models.CharField(max_length=6),
        ),
    ]
