# Generated by Django 5.1.5 on 2025-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_answer_options_alter_test_assessment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtestlink',
            name='created_at',
        ),
        migrations.AddField(
            model_name='generatedtestlink',
            name='assessment_id',
            field=models.CharField(default=16993, max_length=6),
            preserve_default=False,
        ),
    ]
