# Generated by Django 5.1.5 on 2025-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_generatedtestlink_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='group_id',
            field=models.CharField(default=123, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='assessment_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
