# Generated by Django 5.1.5 on 2025-02-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_subject_test_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
