# Generated by Django 5.1.5 on 2025-02-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_rename_subject_id_test_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='assessment_id',
            field=models.CharField(default=1234, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='exams.question'),
        ),
    ]
